# to load data

In [1]:
import pandas as pd
import sqlite3

df = pd.read_csv(
    "../data/logistics_heavy.csv"
)

df.head()

,shipment_id,order_id,customer_name,origin_city,destination_city,origin_country,destination_country,ship_date,delivery_date,weight_kg,volume_m3,shipping_mode,status,base_cost_usd,surcharge_usd,total_cost_usd,currency,payment_terms,created_at,last_update
0,SHP-288390,53737,nguyen kim,Phnom Penh,Saigon,TH,Cambodia,"Oct 15, 2021","Jan 14, 2021",301.9,2.497,rail,LOST,1259.14,726.46,2305.8,THB,PrePaid,2023-02-21T13:50:23Z,2023-07-06T05:55:19Z
1,74871,382273,Vann Lee,Bangkok,Phnom Penh,Cambodia,VN,05/14/2022,08/08/2021,269.53,1.862,TRK,DELIVERED,"99,0",free,NaN,NaN,cod,2023-10-11 00:25:04,2023-10-02T09:42:53Z
2,918399,ORD-399488,Dara Smith,Bangkok,Phnompenh,NaN,Vietnam,04/03/2021,2020-11-18,488.99,2.648,trk,DELIVERED,849.16,1080.9,error,usd,cod,29/10/2023 20:10,2023-05-07 08:10:51
3,SHP-070675,ORD-37150,Nguyen Lee,HCMC,HCMC,Thailand,VN,"Aug 10, 2024","Sep 05, 2020",54.72,3.523,Air Freight,INTRANSIT,155.39,1712.65,1868.04,NaN,prepaid,2023-04-20 14:36:05,2023-05-02 06:03:18
4,823268,ORD-382996,Nguyen Garcia,Phnom Penh,Phnom Penh,VNM,NaN,2025-09-11,NaN,201.95,1.766,air,LOST,636.16,1341.1,1977.2599999999998,KHR,credit 30d,2023-02-07 00:20:20,2023-10-16 03:38:24

In [2]:
conn = sqlite3.connect(
    "../database/data.sqlite"
)

df.to_sql(
    name="logistics_data",
    con=conn,
    if_exists="replace",
    index=False
)

400000

In [3]:
test_df = pd.read_sql(
    "SELECT * FROM logistics_data LIMIT 5",
    conn
)

test_df

,shipment_id,order_id,customer_name,origin_city,destination_city,origin_country,destination_country,ship_date,delivery_date,weight_kg,volume_m3,shipping_mode,status,base_cost_usd,surcharge_usd,total_cost_usd,currency,payment_terms,created_at,last_update
0,SHP-288390,53737,nguyen kim,Phnom Penh,Saigon,TH,Cambodia,"Oct 15, 2021","Jan 14, 2021",301.9,2.497,rail,LOST,1259.14,726.46,2305.8,THB,PrePaid,2023-02-21T13:50:23Z,2023-07-06T05:55:19Z
1,74871,382273,Vann Lee,Bangkok,Phnom Penh,Cambodia,VN,05/14/2022,08/08/2021,269.53,1.862,TRK,DELIVERED,"99,0",free,NaN,NaN,cod,2023-10-11 00:25:04,2023-10-02T09:42:53Z
2,918399,ORD-399488,Dara Smith,Bangkok,Phnompenh,NaN,Vietnam,04/03/2021,2020-11-18,488.99,2.648,trk,DELIVERED,849.16,1080.9,error,usd,cod,29/10/2023 20:10,2023-05-07 08:10:51
3,SHP-070675,ORD-37150,Nguyen Lee,HCMC,HCMC,Thailand,VN,"Aug 10, 2024","Sep 05, 2020",54.72,3.523,Air Freight,INTRANSIT,155.39,1712.65,1868.04,NaN,prepaid,2023-04-20 14:36:05,2023-05-02 06:03:18
4,823268,ORD-382996,Nguyen Garcia,Phnom Penh,Phnom Penh,VNM,NaN,2025-09-11,NaN,201.95,1.766,air,LOST,636.16,1341.1,1977.2599999999998,KHR,credit 30d,2023-02-07 00:20:20,2023-10-16 03:38:24

In [4]:

test_df = pd.read_sql(
    "SELECT * FROM logistics_data LIMIT 5",
    conn
)

test_df

,shipment_id,order_id,customer_name,origin_city,destination_city,origin_country,destination_country,ship_date,delivery_date,weight_kg,volume_m3,shipping_mode,status,base_cost_usd,surcharge_usd,total_cost_usd,currency,payment_terms,created_at,last_update
0,SHP-288390,53737,nguyen kim,Phnom Penh,Saigon,TH,Cambodia,"Oct 15, 2021","Jan 14, 2021",301.9,2.497,rail,LOST,1259.14,726.46,2305.8,THB,PrePaid,2023-02-21T13:50:23Z,2023-07-06T05:55:19Z
1,74871,382273,Vann Lee,Bangkok,Phnom Penh,Cambodia,VN,05/14/2022,08/08/2021,269.53,1.862,TRK,DELIVERED,"99,0",free,NaN,NaN,cod,2023-10-11 00:25:04,2023-10-02T09:42:53Z
2,918399,ORD-399488,Dara Smith,Bangkok,Phnompenh,NaN,Vietnam,04/03/2021,2020-11-18,488.99,2.648,trk,DELIVERED,849.16,1080.9,error,usd,cod,29/10/2023 20:10,2023-05-07 08:10:51
3,SHP-070675,ORD-37150,Nguyen Lee,HCMC,HCMC,Thailand,VN,"Aug 10, 2024","Sep 05, 2020",54.72,3.523,Air Freight,INTRANSIT,155.39,1712.65,1868.04,NaN,prepaid,2023-04-20 14:36:05,2023-05-02 06:03:18
4,823268,ORD-382996,Nguyen Garcia,Phnom Penh,Phnom Penh,VNM,NaN,2025-09-11,NaN,201.95,1.766,air,LOST,636.16,1341.1,1977.2599999999998,KHR,credit 30d,2023-02-07 00:20:20,2023-10-16 03:38:24

# Clean Data -- Naly

In [5]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

df = pd.read_csv('../data/logistics_heavy.csv')
df_original = df.copy()

print(f"Shape: {df.shape}")
df.info()

Shape: (400000, 20)
<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   shipment_id          360002 non-null  str
 1   order_id             339961 non-null  str
 2   customer_name        372181 non-null  str
 3   origin_city          388144 non-null  str
 4   destination_city     387894 non-null  str
 5   origin_country       337830 non-null  str
 6   destination_country  337802 non-null  str
 7   ship_date            388076 non-null  str
 8   delivery_date        359616 non-null  str
 9   weight_kg            380039 non-null  str
 10  volume_m3            360064 non-null  float64
 11  shipping_mode        379958 non-null  str
 12  status               388216 non-null  str
 13  base_cost_usd        400000 non-null  str
 14  surcharge_usd        400000 non-null  str
 15  total_cost_usd       328569 non-null  str
 16  currency             317313 non-null  str
 17  payment_terms        315302 non-null  str
 18  created_at           400000 non-null  str
 19  last_update          400000 non-null  str
dtypes: float64(1), str(19)
memory usage: 61.0 MB

In [58]:
print("=== Dtype Check ===")
print(df[['weight_kg', 'volume_m3', 'base_cost_usd', 'surcharge_usd', 'total_cost_usd']].dtypes)

=== Dtype Check ===
weight_kg             str
volume_m3         float64
base_cost_usd         str
surcharge_usd         str
total_cost_usd        str
dtype: object

In [6]:
for col in ['weight_kg', 'base_cost_usd', 'surcharge_usd', 'total_cost_usd']:
    # Try converting to numeric; anything that fails becomes NaN
    converted = pd.to_numeric(df[col], errors='coerce')
    failed_mask = converted.isna() & df[col].notna()  # failed conversion but wasn't already null
    failed_values = df.loc[failed_mask, col].unique()
    print(f"\n{col}: {failed_mask.sum()} non-numeric values")
    print(f"  Unique garbage strings: {failed_values[:10]}")

weight_kg: 18977 non-numeric values
  Unique garbage strings: <StringArray>
['unknown']
Length: 1, dtype: str

base_cost_usd: 48098 non-numeric values
  Unique garbage strings: <StringArray>
[   '99,0',  '986,03', '1218,55', '1358,37',  '583,97',  '$82.63',    'free',
 '1210,39', '$202.45', '1934,49']
Length: 10, dtype: str

surcharge_usd: 48266 non-numeric values
  Unique garbage strings: <StringArray>
[    'free', '$1730.81',   '553,66',  '1365,45',  '$619.99',  '1025,85',
   '196,43', '$1568.82',  '$355.38',  '1682,91']
Length: 10, dtype: str

total_cost_usd: 80119 non-numeric values
  Unique garbage strings: <StringArray>
[  'error',  '670,35',    'free',   '802,6', '1036,35',  '993,09',  '$47.32',
 '1900,18',  '140,45',  '1829,7']
Length: 10, dtype: str

In [7]:
for col in ['weight_kg', 'base_cost_usd', 'surcharge_usd', 'total_cost_usd']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print(df[['weight_kg', 'base_cost_usd', 'surcharge_usd', 'total_cost_usd']].dtypes)

weight_kg         float64
base_cost_usd     float64
surcharge_usd     float64
total_cost_usd    float64
dtype: object

In [8]:
missing_data = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percentage': (df.isnull().sum() / len(df)) * 100
})
missing_data = missing_data[missing_data['Missing_Count'] > 0].sort_values(
    'Missing_Percentage', ascending=False
)
print(missing_data)

                     Missing_Count  Missing_Percentage
total_cost_usd              151550            37.88750
payment_terms                84698            21.17450
currency                     82687            20.67175
destination_country          62198            15.54950
origin_country               62170            15.54250
order_id                     60039            15.00975
surcharge_usd                48266            12.06650
base_cost_usd                48098            12.02450
delivery_date                40384            10.09600
shipment_id                  39998             9.99950
volume_m3                    39936             9.98400
weight_kg                    38938             9.73450
customer_name                27819             6.95475
shipping_mode                20042             5.01050
destination_city             12106             3.02650
ship_date                    11924             2.98100
origin_city                  11856             2.96400
status                       11784             2.94600

In [9]:
print(df[['weight_kg', 'volume_m3', 'base_cost_usd', 'surcharge_usd', 'total_cost_usd']].describe())

           weight_kg      volume_m3  base_cost_usd  surcharge_usd  \
count  361062.000000  360064.000000  351902.000000  351734.000000
mean      766.537556       2.016783    1002.827632    1002.839678
std      4143.680195       0.964707     576.001104     575.571177
min      -100.000000       0.000000       5.010000       5.000000
25%       115.200000       1.326000     503.912500     504.462500
50%       247.340000       2.000000    1002.345000    1001.920000
75%       379.310000       2.674000    1502.100000    1500.977500
max     49996.160000       6.562000    2000.000000    2000.000000

       total_cost_usd
count   248450.000000
mean      1753.771732
std        894.433637
min          5.020000
25%       1090.700000
50%       1728.200000
75%       2370.620000
max       5833.010000

In [10]:
# Check for impossible values
print(f"Negative weight_kg: {(df['weight_kg'] < 0).sum()}")
print(f"Negative base_cost_usd: {(df['base_cost_usd'] < 0).sum()}")
print(f"Negative surcharge_usd: {(df['surcharge_usd'] < 0).sum()}")
print(f"Negative total_cost_usd: {(df['total_cost_usd'] < 0).sum()}")
print(f"Zero weight_kg: {(df['weight_kg'] == 0).sum()}")

Negative weight_kg: 11343
Negative base_cost_usd: 0
Negative surcharge_usd: 0
Negative total_cost_usd: 0
Zero weight_kg: 0

In [11]:
df['calculated_total'] = df['base_cost_usd'] + df['surcharge_usd']
df['cost_diff'] = (df['total_cost_usd'] - df['calculated_total']).abs()

inconsistent = df[df['cost_diff'] > 0.01]
print(f"Rows where total_cost_usd doesn't match base+surcharge: {len(inconsistent)}")
print(inconsistent[['base_cost_usd', 'surcharge_usd', 'total_cost_usd', 'calculated_total']].head())

Rows where total_cost_usd doesn't match base+surcharge: 54885
    base_cost_usd  surcharge_usd  total_cost_usd  calculated_total
0         1259.14         726.46         2305.80           1985.60
5         1483.76         858.24         3239.24           2342.00
14         829.43         726.75         1521.18           1556.18
27        1258.37        1471.70         2855.69           2730.07
34         204.89         947.45         1929.21           1152.34

In [12]:
# weight_kg: numeric, moderate missing (~5-9%) — impute with median (robust to outliers)
median_weight = df['weight_kg'].median()
df['weight_kg'] = df['weight_kg'].fillna(median_weight)

# volume_m3: numeric, ~10% missing — median imputation
median_volume = df['volume_m3'].median()
df['volume_m3'] = df['volume_m3'].fillna(median_volume)

# base_cost_usd / surcharge_usd: 'free' likely means legitimate $0, not missing
# Decision: treat former 'free' as 0, not impute with median
df['base_cost_usd'] = df['base_cost_usd'].fillna(0)
df['surcharge_usd'] = df['surcharge_usd'].fillna(0)

# total_cost_usd: high corruption (~36% combined) — recompute from components
# instead of imputing blindly, since you have the raw components
df['total_cost_usd'] = df['total_cost_usd'].fillna(df['base_cost_usd'] + df['surcharge_usd'])

In [13]:
df = df.drop(columns=['calculated_total', 'cost_diff'], errors='ignore')

# Final check — these 5 columns must now be fully numeric with zero nulls
target_cols = ['weight_kg', 'volume_m3', 'base_cost_usd', 'surcharge_usd', 'total_cost_usd']
print(df[target_cols].dtypes)
print(df[target_cols].isnull().sum())

weight_kg         float64
volume_m3         float64
base_cost_usd     float64
surcharge_usd     float64
total_cost_usd    float64
dtype: object
weight_kg         0
volume_m3         0
base_cost_usd     0
surcharge_usd     0
total_cost_usd    0
dtype: int64

In [14]:
df.to_csv('../data/logistics_after_naly.csv', index=False)
print("✅ Naly's task complete. Handed off to David for duplicate removal.")

✅ Naly's task complete. Handed off to David for duplicate removal.

# Duplicate Data Handler -- David task

In [15]:
df.duplicated(subset=['shipment_id']).sum()

np.int64(74829)

In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/logistics_after_naly.csv')
df_original = df.copy()

print(f"Shape: {df.shape}")
df.info()

Shape: (400000, 20)
<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   shipment_id          360002 non-null  str
 1   order_id             339961 non-null  str
 2   customer_name        372181 non-null  str
 3   origin_city          388144 non-null  str
 4   destination_city     387894 non-null  str
 5   origin_country       337830 non-null  str
 6   destination_country  337802 non-null  str
 7   ship_date            388076 non-null  str
 8   delivery_date        359616 non-null  str
 9   weight_kg            400000 non-null  float64
 10  volume_m3            400000 non-null  float64
 11  shipping_mode        379958 non-null  str
 12  status               388216 non-null  str
 13  base_cost_usd        400000 non-null  float64
 14  surcharge_usd        400000 non-null  float64
 15  total_cost_usd       400000 non-null  float64
 16  currency             317313 non-null  str
 17  payment_terms        315302 non-null  str
 18  created_at           400000 non-null  str
 19  last_update          400000 non-null  str
dtypes: float64(5), str(15)
memory usage: 61.0 MB

In [17]:
print(f"Null shipment_id count: {df['shipment_id'].isnull().sum()}")

Null shipment_id count: 39998

In [18]:
# Isolate rows with missing shipment_id — these are a SEPARATE issue, not duplicates
null_id_rows = df[df['shipment_id'].isnull()]
print(f"Rows with missing shipment_id: {len(null_id_rows)}")

# Now check duplicates ONLY on rows that have a valid ID
df_valid_id = df[df['shipment_id'].notna()]
true_duplicate_count = df_valid_id.duplicated(subset=['shipment_id']).sum()
print(f"TRUE duplicate shipment_ids (excluding nulls): {true_duplicate_count}")

Rows with missing shipment_id: 39998
TRUE duplicate shipment_ids (excluding nulls): 34832

In [19]:
# Get all rows that share a shipment_id with at least one other row
dup_mask = df_valid_id.duplicated(subset=['shipment_id'], keep=False)
dup_groups = df_valid_id[dup_mask].sort_values('shipment_id')

print(f"Total rows involved in shipment_id duplication: {len(dup_groups)}")
dup_groups.head(20)

Total rows involved in shipment_id duplication: 67056

,shipment_id,order_id,customer_name,origin_city,destination_city,origin_country,destination_country,ship_date,delivery_date,weight_kg,volume_m3,shipping_mode,status,base_cost_usd,surcharge_usd,total_cost_usd,currency,payment_terms,created_at,last_update
60177,100026,ORD-222331,Lina Smith,BKK,Bangkok,Thailand,TH,10/17/2022,10/16/2025,438.13,2.748,air,returned,827.27,696.56,1212.26,USD,prepaid,2023-10-19T18:39:10Z,2023-08-20 21:00:46
202984,100026,402798,Maria Garcia,Bangkok,Bangkok,Vietnam,KHM,2020-03-27,07/11/2022,469.04,2.289,sea,??,0.00,476.60,1744.87,VND,cod,2023-05-19 07:44:52,03/09/2023 05:13
227731,100053,ORD-68371,Chan Kim,HCMC,Ho Chi Minh,KH,NaN,04/11/22,"Nov 24, 2023",31369.14,2.275,trk,Delivered,1631.30,418.37,2049.67,VND,cod,2023-10-25 23:05:29,2023-12-21T23:04:27Z
205189,100053,NaN,Srey Nguyen,Saigon,BKK,VN,KH,31/12/21,04/26/2024,412.00,2.583,trk,lost,0.00,728.62,728.62,KHR,NaN,2023-09-21 15:48:00,2023-03-20 17:11:38
226243,10006,191681,Maria Smith,Ho Chi Minh,BKK,VNM,TH,27/10/25,NaN,310.02,1.623,sea,INTRANSIT,556.65,1005.80,1562.45,USD,collect,2023-03-04 18:47:54,2023-10-15 02:35:27
216767,10006,ORD-138345,john tran,Phnompenh,Phnompenh,TH,TH,03/13/2025,2020-08-25,107.95,2.808,air,lost,913.50,966.73,1880.23,KHR,collect,19/03/2023 13:33,2023-11-20 03:00:47
46284,100106,248485,Maria Garcia,Phnom Penh,Bangkok,VNM,Cambodia,09/02/21,32/13/2024,247.34,1.053,trk,??,1986.28,0.00,1986.28,THB,NaN,2023-11-11 13:33:15,2023-03-14T06:45:15Z
78086,100106,ORD-470773,Nguyen Nguyen,PP,Bangkok,Thailand,VN,07/09/21,2021-08-16,344.22,2.000,rail,??,662.38,705.38,1367.76,KHR,collect,2023-07-15 13:50:07,2023-12-10 23:23:12
286766,100183,ORD-447787,NaN,PP,Saigon,NaN,NaN,2021-06-26,10/14/2022,21.69,2.000,sea,delivered,1571.04,416.12,1987.16,VND,collect,2023-04-07 10:50:32,2023-07-10 14:42:05
114398,100183,NaN,Lina Lee,BKK,HCMC,NaN,NaN,2021-07-06,16/09/23,247.34,2.088,AIR,RETURNED,1541.04,1393.62,2934.66,USD,PrePaid,05/10/2023 18:23,0000-00-00
136695,100186,164379,Nguyen Lee,Saigon,BKK,KHM,Vietnam,2022-06-13,01/16/2024,122.81,2.213,air,in transit,0.00,0.00,0.00,KHR,collect,2023-07-30 11:29:20,2023-06-15T13:21:54Z
275966,100186,63325,John Nguyen,Saigon,Ho Chi Minh,KHM,VN,2021-11-17,NaN,347.52,0.617,trk,lost,0.00,1661.22,1661.22,KHR,collect,2023-06-05T02:22:35Z,09/10/2023 01:21
274583,100190,ORD-244927,Sok Garcia,Ho Chi Minh,NaN,Cambodia,Cambodia,"Mar 18, 2020",2021-11-01,226.01,2.354,AIR,Delivered,1601.73,1469.93,3071.66,KHR,PrePaid,2023-10-13T19:10:56Z,2023-06-23 16:46:36
200816,100190,ORD-297172,Maria Tran,Phnom Penh,Bangkok,VN,KHM,2025-08-07,"Dec 24, 2023",247.34,2.115,rail,INTRANSIT,1357.05,0.00,1357.05,VND,credit 30d,2023-06-07 08:05:59,2023-08-12 16:11:50
229158,100207,ORD-294464,Maria Nguyen,Phnom Penh,Ho Chi Minh,Vietnam,Thailand,03/28/2020,"Jul 12, 2023",75.71,0.732,trk,??,1816.75,90.02,1906.77,KHR,collect,2023-11-15 19:54:43,2023-06-12 19:26:00
389993,100207,ORD-72920,MARIA GARCIA,HCMC,HCMC,NaN,VN,21/11/22,10/15/2025,29.21,1.476,AIR,in transit,1798.28,1439.33,3237.61,usd,NaN,2023-12-09 09:29:42,2023-03-19T20:25:32Z
396481,100268,ORD-81839,Nguyen Garcia,Ho Chi Minh,PP,TH,Thailand,2024-05-15,2022-03-21,267.22,2.357,truck,in transit,1947.20,1716.63,743.31,usd,collect,2023-10-06 16:32:10,25/06/2023 09:24
300737,100268,ORD-156655,Dara Nguyen,PP,Ho Chi Minh,Thailand,NaN,2021-11-27,2020-09-21,259.10,2.937,sea,RETURNED,275.82,176.61,547.70,usd,credit 30d,26/04/2023 17:31,2023-03-25 06:28:32
367213,10028,43303,Lina Smith,BKK,Phnompenh,NaN,VN,"Jun 18, 2021",06/26/2023,222.58,1.717,Air Freight,returned,1584.73,1840.01,3424.74,VND,NaN,2023-10-23 06:50:09,2023-09-06T15:15:05Z
272623,10028,ORD-493933,Chan Nguyen,PP,Phnom Penh,TH,NaN,"Sep 23, 2023","Apr 08, 2020",287.98,2.507,Air Freight,delivered,1402.79,586.65,1989.44,THB,credit 30d,2023-04-04T20:44:20Z,2023-04-10 00:49:09

In [20]:
sample_id = dup_groups['shipment_id'].iloc[0]
print(df_valid_id[df_valid_id['shipment_id'] == sample_id])

       shipment_id    order_id customer_name origin_city destination_city  \
60177       100026  ORD-222331    Lina Smith         BKK          Bangkok
202984      100026      402798  Maria Garcia     Bangkok          Bangkok

       origin_country destination_country   ship_date delivery_date  \
60177        Thailand                  TH  10/17/2022    10/16/2025
202984        Vietnam                 KHM  2020-03-27    07/11/2022

        weight_kg  volume_m3 shipping_mode    status  base_cost_usd  \
60177      438.13      2.748           air  returned         827.27
202984     469.04      2.289           sea        ??           0.00

        surcharge_usd  total_cost_usd currency payment_terms  \
60177          696.56         1212.26      USD       prepaid
202984         476.60         1744.87      VND           cod

                  created_at          last_update
60177   2023-10-19T18:39:10Z  2023-08-20 21:00:46
202984   2023-05-19 07:44:52     03/09/2023 05:13

In [21]:
exact_duplicates = df.duplicated(keep=False)
print(f"Fully identical duplicate rows (all 20 columns match): {exact_duplicates.sum()}")

df[exact_duplicates].sort_values('shipment_id').head(10)

Fully identical duplicate rows (all 20 columns match): 0

Empty DataFrame
Columns: [shipment_id, order_id, customer_name, origin_city, destination_city, origin_country, destination_country, ship_date, delivery_date, weight_kg, volume_m3, shipping_mode, status, base_cost_usd, surcharge_usd, total_cost_usd, currency, payment_terms, created_at, last_update]
Index: []

In [22]:
df = df.drop_duplicates(keep='first')
print(f"Shape after removing exact duplicates: {df.shape}")

Shape after removing exact duplicates: (400000, 20)

In [23]:
# Sort so the latest last_update is last, then keep last occurrence
df['last_update'] = pd.to_datetime(df['last_update'], errors='coerce')

df = df.sort_values('last_update').drop_duplicates(subset=['shipment_id'], keep='last')
print(f"Shape after keeping latest record per shipment: {df.shape}")

Shape after keeping latest record per shipment: (325171, 20)

In [24]:
df = df.drop_duplicates(subset=['shipment_id'], keep='first')
print(f"Shape after deduplication: {df.shape}")

Shape after deduplication: (325171, 20)

In [25]:
print(f"Rows with no shipment_id at all: {df['shipment_id'].isnull().sum()}")

# Option 1: drop them — no reliable way to deduplicate or join them later
df = df.dropna(subset=['shipment_id'])

# Option 2 (only if you have time/justification): generate a synthetic ID
# df['shipment_id'] = df['shipment_id'].fillna(
#     'GEN-' + df.index.astype(str)
# )

Rows with no shipment_id at all: 1

In [28]:
order_dup_count = df[df['order_id'].notna()].duplicated(subset=['order_id']).sum()
print(f"Duplicate order_ids: {order_dup_count}")

# 1. Isolate valid order IDs first
df_valid_orders = df[df['order_id'].notna()]

# 2. Find duplicates within that clean subset
sample_order = df_valid_orders.duplicated(subset=['order_id'], keep=False)

# 3. Safely index and view the sample rows
df_valid_orders[sample_order].sort_values('order_id').head(10)

Duplicate order_ids: 36228

,shipment_id,order_id,customer_name,origin_city,destination_city,origin_country,destination_country,ship_date,delivery_date,weight_kg,volume_m3,shipping_mode,status,base_cost_usd,surcharge_usd,total_cost_usd,currency,payment_terms,created_at,last_update
151202,419565,100043,John Smith,Saigon,Bangkok,NaN,TH,"Nov 26, 2024",05/12/24,478.36,2.000,Sea,??,500.34,1687.69,2188.03,USD,prepaid,2023-05-10T06:47:21Z,NaT
246772,758532,100043,Srey Kim,Phnom Penh,Phnom Penh,Vietnam,KHM,09/16/2021,07/06/24,50.76,0.526,rail,returned,783.76,1359.24,2143.00,THB,PrePaid,2023-07-04 06:06:26,2023-04-23 02:49:12+00:00
19160,SHP-471760,100097,Maria Nguyen,PP,HCMC,Cambodia,Cambodia,"Aug 06, 2020",2020-10-07,404.15,2.270,truck,returned,1225.88,1243.55,1668.71,VND,PrePaid,2023-08-04 21:41:37,NaT
309786,382355,100097,DARA KIM,BKK,Bangkok,Cambodia,VN,04/09/25,2025-05-10,107.62,3.335,sea,Delivered,461.03,939.51,1300.52,VND,cod,2023-01-13T03:44:00Z,2023-07-26 09:02:57+00:00
338648,699156,100099,Nguyen Lee,Bangkok,BKK,Vietnam,KHM,25/04/21,"Jan 16, 2022",264.25,0.961,rail,RETURNED,134.26,485.54,791.60,NaN,prepaid,2023-04-05 18:09:44,NaT
317845,295719,100099,Sok Nguyen,Saigon,Phnompenh,Cambodia,KHM,10/27/2020,2025-11-08,286.67,2.000,sea,DELIVERED,1813.41,434.57,2247.98,THB,cod,2023-11-16 22:39:47,NaT
69289,SHP-002685,100148,MARIA NGUYEN,Ho Chi Minh,HCMC,Thailand,Thailand,"Feb 13, 2021",09/19/2025,95.36,2.527,Air Freight,RETURNED,1085.71,505.78,1591.49,NaN,prepaid,28/02/2023 04:03,NaT
143965,377022,100148,Chan Smith,Ho Chi Minh,PP,KHM,Thailand,2023-12-27,02/19/2023,42.21,3.583,Sea,DELIVERED,1235.54,1807.29,2636.09,VND,NaN,27/08/2023 07:56,NaT
307059,SHP-191107,100186,Sok Smith,Phnom Penh,BKK,KHM,NaN,02/11/2021,"Jan 24, 2025",287.21,1.643,truck,INTRANSIT,217.46,1086.47,1303.93,VND,prepaid,2023-05-09 09:45:33,2023-02-02 11:36:00+00:00
348611,939699,100186,Lina Tran,PP,PP,KHM,Vietnam,2022-06-07,2022-10-26,-42.17,1.339,TRK,LOST,1432.79,1184.98,2617.77,USD,cod,2023-03-06T00:30:57Z,NaT

In [29]:
print("=== FINAL DUPLICATE AUDIT ===")
print(f"Exact full-row duplicates remaining: {df.duplicated().sum()}")
print(f"Duplicate shipment_ids remaining: {df.duplicated(subset=['shipment_id']).sum()}")
print(f"Null shipment_ids remaining: {df['shipment_id'].isnull().sum()}")
print(f"\nOriginal shape: {df_original.shape}")
print(f"Final shape:    {df.shape}")
print(f"Rows removed:   {df_original.shape[0] - df.shape[0]}")

=== FINAL DUPLICATE AUDIT ===
Exact full-row duplicates remaining: 0
Duplicate shipment_ids remaining: 0
Null shipment_ids remaining: 0

Original shape: (400000, 20)
Final shape:    (325170, 20)
Rows removed:   74830

In [30]:
df.to_csv('../data/logistics_after_david.csv', index=False)
print("✅ David's task complete. Handed off to Menghong for date/time processing.")

✅ David's task complete. Handed off to Menghong for date/time processing.

# Date and Time Handler -- Menghong

In [31]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/logistics_after_david.csv')
df_original = df.copy()

print(f"Shape: {df.shape}")
df[['ship_date','delivery_date','created_at','last_update']].dtypes

Shape: (325170, 20)

ship_date        str
delivery_date    str
created_at       str
last_update      str
dtype: object

In [32]:
assert df['shipment_id'].isnull().sum() == 0, "David's handoff incomplete — shipment_id has nulls"
assert df.duplicated(subset=['shipment_id']).sum() == 0, "David's handoff incomplete — duplicates remain"

In [34]:
import pandas as pd

date_cols = ['ship_date', 'delivery_date', 'created_at', 'last_update']

for col in date_cols:
    print(f"\n=== {col} ===")
    print(f"Null count (raw): {df[col].isnull().sum()}")
    
    # Fix: Added utc=True to normalize mixed timezones into UTC during test parsing
    test_parse = pd.to_datetime(df[col], errors='coerce', format='mixed', utc=True)
    
    # Isolate strings that failed to parse completely
    garbage_mask = test_parse.isna() & df[col].notna()
    garbage_values = df.loc[garbage_mask, col].value_counts().head(5)
    
    print(f"Unparseable non-null values: {garbage_mask.sum()}")
    print(f"Top garbage patterns:\n{garbage_values}")

=== ship_date ===
Null count (raw): 9713
Unparseable non-null values: 3068
Top garbage patterns:
ship_date
32/13/2024    3068
Name: count, dtype: int64

=== delivery_date ===
Null count (raw): 32743
Unparseable non-null values: 2844
Top garbage patterns:
delivery_date
32/13/2024    2844
Name: count, dtype: int64

=== created_at ===
Null count (raw): 0
Unparseable non-null values: 6534
Top garbage patterns:
created_at
0000-00-00    6534
Name: count, dtype: int64

=== last_update ===
Null count (raw): 251382
Unparseable non-null values: 0
Top garbage patterns:
Series([], Name: count, dtype: int64)

In [36]:
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce', format='mixed', utc=True)

print(df[date_cols].dtypes)

ship_date        datetime64[us, UTC]
delivery_date    datetime64[us, UTC]
created_at       datetime64[us, UTC]
last_update      datetime64[us, UTC]
dtype: object

In [37]:
missing_after = pd.DataFrame({
    'Missing_Count': df[date_cols].isnull().sum(),
    'Missing_Pct': (df[date_cols].isnull().sum() / len(df) * 100).round(2)
})
print(missing_after)

               Missing_Count  Missing_Pct
ship_date              12781         3.93
delivery_date          35587        10.94
created_at              6534         2.01
last_update           251382        77.31

In [38]:
# These can't be reliably imputed — a guessed ship date would corrupt
# downstream delivery_days calculation. Drop rows where BOTH are missing.
both_missing = df['ship_date'].isnull() & df['delivery_date'].isnull()
print(f"Rows missing both ship_date AND delivery_date: {both_missing.sum()}")
df = df[~both_missing]

Rows missing both ship_date AND delivery_date: 1411

In [39]:
one_missing = df['ship_date'].isnull() | df['delivery_date'].isnull()
print(f"Rows missing exactly one of ship_date/delivery_date: {one_missing.sum()}")
df = df[~one_missing]

Rows missing exactly one of ship_date/delivery_date: 45546

In [40]:
# These are record-tracking timestamps, not business-critical shipment dates.
# If missing, fill with ship_date as a reasonable proxy (record created ~when shipped)
df['created_at'] = df['created_at'].fillna(df['ship_date'])
df['last_update'] = df['last_update'].fillna(df['delivery_date'])

In [41]:
invalid_order = df[df['delivery_date'] < df['ship_date']]
print(f"Rows where delivery_date is BEFORE ship_date: {len(invalid_order)}")
print(invalid_order[['shipment_id', 'ship_date', 'delivery_date']].head(10))

Rows where delivery_date is BEFORE ship_date: 138714
   shipment_id                 ship_date             delivery_date
0   SHP-759474 2024-12-21 00:00:00+00:00 2024-06-26 00:00:00+00:00
6        31041 2021-04-08 00:00:00+00:00 2021-03-03 00:00:00+00:00
7   SHP-958819 2025-03-07 00:00:00+00:00 2024-02-14 00:00:00+00:00
8       899972 2023-10-24 00:00:00+00:00 2020-10-27 00:00:00+00:00
9   SHP-875812 2024-04-03 00:00:00+00:00 2022-01-25 00:00:00+00:00
10      857439 2025-01-10 00:00:00+00:00 2024-10-25 00:00:00+00:00
13      970666 2024-06-27 00:00:00+00:00 2021-12-04 00:00:00+00:00
17      944087 2020-10-02 00:00:00+00:00 2020-09-17 00:00:00+00:00
21  SHP-209647 2025-05-07 00:00:00+00:00 2021-05-02 00:00:00+00:00
22  SHP-334563 2025-06-05 00:00:00+00:00 2023-01-09 00:00:00+00:00

In [42]:
# If confirmed as data-entry reversal pattern:
# df.loc[invalid_order.index, ['ship_date','delivery_date']] = df.loc[invalid_order.index, ['delivery_date','ship_date']].values

# If confirmed as genuine corruption with no recoverable pattern:
df = df[df['delivery_date'] >= df['ship_date']]

In [43]:
# From ship_date
df['ship_year']    = df['ship_date'].dt.year
df['ship_month']   = df['ship_date'].dt.month
df['ship_day']     = df['ship_date'].dt.day
df['ship_weekday'] = df['ship_date'].dt.dayofweek   # Monday=0, Sunday=6
df['ship_weekday_name'] = df['ship_date'].dt.day_name()

# From delivery_date — same extraction
df['delivery_year']    = df['delivery_date'].dt.year
df['delivery_month']   = df['delivery_date'].dt.month
df['delivery_weekday'] = df['delivery_date'].dt.dayofweek

In [44]:
df['delivery_days'] = (df['delivery_date'] - df['ship_date']).dt.days

print(df['delivery_days'].describe())

# Sanity check — negative values should be zero now (fixed in Step 6),
# but extreme outliers (e.g. 500+ day delivery) still need inspection
extreme_delivery = df[df['delivery_days'] > 90]
print(f"Shipments with >90 day delivery: {len(extreme_delivery)}")

count    139499.000000
mean        729.315966
std         516.704521
min           0.000000
25%         291.000000
50%         641.000000
75%        1095.000000
max        2186.000000
Name: delivery_days, dtype: float64
Shipments with >90 day delivery: 128141

In [45]:
print("=== FINAL DATE AUDIT ===")
print(df[['ship_date','delivery_date','created_at','last_update']].isnull().sum())
print(f"\nNegative delivery_days remaining: {(df['delivery_days'] < 0).sum()}")
print(f"\nOriginal shape: {df_original.shape}")
print(f"Final shape:    {df.shape}")
print(f"Rows removed:   {df_original.shape[0] - df.shape[0]}")

=== FINAL DATE AUDIT ===
ship_date        0
delivery_date    0
created_at       0
last_update      0
dtype: int64

Negative delivery_days remaining: 0

Original shape: (325170, 20)
Final shape:    (139499, 29)
Rows removed:   185671

In [46]:
df.to_csv('../data/logistics_after_menghong.csv', index=False)
print("✅ Menghong's task complete. Handed off to Tong for business logic.")

✅ Menghong's task complete. Handed off to Tong for business logic.

# Business Logic Developer -- Tong

In [47]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/logistics_after_menghong.csv')
df_original = df.copy()

print(f"Shape: {df.shape}")

Shape: (139499, 29)

In [48]:
print("Before:", df['shipping_mode'].unique())

mode_map = {
    'air': 'Air', 'AIR': 'Air', 'Air Freight': 'Air',
    'sea': 'Sea', 'Sea': 'Sea',
    'trk': 'Truck', 'TRK': 'Truck', 'truck': 'Truck',
    'rail': 'Rail'
}
df['shipping_mode'] = df['shipping_mode'].map(mode_map).fillna(df['shipping_mode'])

print("After:", df['shipping_mode'].value_counts())

Before: <StringArray>
['rail', 'AIR', 'Sea', 'trk', 'Air Freight', 'sea', 'air', 'TRK', nan,
 'truck']
Length: 10, dtype: str
After: shipping_mode
Air      44202
Truck    44112
Sea      29480
Rail     14605
Name: count, dtype: int64

In [49]:
print("Before:", df['status'].unique())

status_map = {
    'in transit': 'In Transit', 'INTRANSIT': 'In Transit',
    'lost': 'Lost', 'LOST': 'Lost',
    'delivered': 'Delivered', 'DELIVERED': 'Delivered', 'Delivered': 'Delivered',
    'returned': 'Returned', 'RETURNED': 'Returned',
    '??': np.nan   # explicit unknown placeholder — treat as missing, not a category
}
df['status'] = df['status'].map(status_map).fillna(df['status'])

print("After:\n", df['status'].value_counts())
print(f"\nNull status after mapping '??': {df['status'].isnull().sum()}")

Before: <StringArray>
[      'lost',  'INTRANSIT',   'returned',  'DELIVERED',  'delivered',
  'Delivered', 'in transit',         '??',       'LOST',   'RETURNED',
          nan]
Length: 11, dtype: str
After:
 status
Delivered     40643
In Transit    27318
Lost          27155
Returned      26856
??            13459
Name: count, dtype: int64

Null status after mapping '??': 4068

In [50]:
# Decide: drop rows with unknown status, or keep as a separate 'Unknown' category?
# For a prediction model, an unresolved status is itself informative — keep it labeled.
df['status'] = df['status'].fillna('Unknown')

In [51]:
city_map = {
    'BKK': 'Bangkok', 'Bangkok': 'Bangkok',
    'PP': 'Phnom Penh', 'Phnompenh': 'Phnom Penh', 'Phnom Penh': 'Phnom Penh',
    'Saigon': 'Ho Chi Minh', 'HCMC': 'Ho Chi Minh', 'Ho Chi Minh': 'Ho Chi Minh'
}
df['origin_city'] = df['origin_city'].map(city_map).fillna(df['origin_city'])
df['destination_city'] = df['destination_city'].map(city_map).fillna(df['destination_city'])

print(df['origin_city'].value_counts())
print(df['destination_city'].value_counts())

origin_city
Phnom Penh     51053
Ho Chi Minh    50665
Bangkok        33693
Name: count, dtype: int64
destination_city
Phnom Penh     50858
Ho Chi Minh    50783
Bangkok        33644
Name: count, dtype: int64

In [52]:
country_map = {
    'VN': 'Vietnam', 'VNM': 'Vietnam', 'Vietnam': 'Vietnam',
    'KH': 'Cambodia', 'KHM': 'Cambodia', 'Cambodia': 'Cambodia',
    'TH': 'Thailand', 'Thailand': 'Thailand'
}
df['origin_country'] = df['origin_country'].map(country_map).fillna(df['origin_country'])
df['destination_country'] = df['destination_country'].map(country_map).fillna(df['destination_country'])

print(df['origin_country'].value_counts())
print(df['destination_country'].value_counts())

origin_country
Cambodia    44204
Vietnam     43951
Thailand    29526
Name: count, dtype: int64
destination_country
Vietnam     44226
Cambodia    44164
Thailand    29430
Name: count, dtype: int64

In [53]:
df['currency'] = df['currency'].str.upper()
print(df['currency'].value_counts())

payment_map = {
    'COD': 'COD', 'cod': 'COD',
    'prepaid': 'Prepaid', 'PrePaid': 'Prepaid',
    'collect': 'Collect',
    'credit 30d': 'Credit 30d'
}
df['payment_terms'] = df['payment_terms'].map(payment_map).fillna(df['payment_terms'])
print(df['payment_terms'].value_counts())

currency
USD    44325
VND    22232
KHR    22136
THB    22017
Name: count, dtype: int64
payment_terms
COD           36771
Prepaid       36486
Collect       18392
Credit 30d    18110
Name: count, dtype: int64

In [54]:
print("=== POST-NORMALIZATION CARDINALITY ===")
for col in ['shipping_mode','status','origin_city','destination_city','origin_country','destination_country','currency','payment_terms']:
    print(f"{col}: {df[col].nunique()} unique values — {sorted(df[col].dropna().unique())}")

=== POST-NORMALIZATION CARDINALITY ===
shipping_mode: 4 unique values — ['Air', 'Rail', 'Sea', 'Truck']
status: 6 unique values — ['??', 'Delivered', 'In Transit', 'Lost', 'Returned', 'Unknown']
origin_city: 3 unique values — ['Bangkok', 'Ho Chi Minh', 'Phnom Penh']
destination_city: 3 unique values — ['Bangkok', 'Ho Chi Minh', 'Phnom Penh']
origin_country: 3 unique values — ['Cambodia', 'Thailand', 'Vietnam']
destination_country: 3 unique values — ['Cambodia', 'Thailand', 'Vietnam']
currency: 4 unique values — ['KHR', 'THB', 'USD', 'VND']
payment_terms: 4 unique values — ['COD', 'Collect', 'Credit 30d', 'Prepaid']

# Feature Engineer -- virak

In [55]:
import pandas as pd
import numpy as np

# You receive data AFTER Tong finishes business_logic.ipynb
# So you load whatever Tong outputs — likely still logistics_heavy.csv
# or a cleaned intermediate file

df = pd.read_csv('../data/logistics_heavy.csv') # we should change form logistics_heavy.csv to final.csv

# Backup
df_original = df.copy()

print(f"Shape: {df.shape}")
print(df.dtypes)
df.head()

Shape: (400000, 20)
shipment_id                str
order_id                   str
customer_name              str
origin_city                str
destination_city           str
origin_country             str
destination_country        str
ship_date                  str
delivery_date              str
weight_kg                  str
volume_m3              float64
shipping_mode              str
status                     str
base_cost_usd              str
surcharge_usd              str
total_cost_usd             str
currency                   str
payment_terms              str
created_at                 str
last_update                str
dtype: object

,shipment_id,order_id,customer_name,origin_city,destination_city,origin_country,destination_country,ship_date,delivery_date,weight_kg,volume_m3,shipping_mode,status,base_cost_usd,surcharge_usd,total_cost_usd,currency,payment_terms,created_at,last_update
0,SHP-288390,53737,nguyen kim,Phnom Penh,Saigon,TH,Cambodia,"Oct 15, 2021","Jan 14, 2021",301.9,2.497,rail,LOST,1259.14,726.46,2305.8,THB,PrePaid,2023-02-21T13:50:23Z,2023-07-06T05:55:19Z
1,74871,382273,Vann Lee,Bangkok,Phnom Penh,Cambodia,VN,05/14/2022,08/08/2021,269.53,1.862,TRK,DELIVERED,"99,0",free,NaN,NaN,cod,2023-10-11 00:25:04,2023-10-02T09:42:53Z
2,918399,ORD-399488,Dara Smith,Bangkok,Phnompenh,NaN,Vietnam,04/03/2021,2020-11-18,488.99,2.648,trk,DELIVERED,849.16,1080.9,error,usd,cod,29/10/2023 20:10,2023-05-07 08:10:51
3,SHP-070675,ORD-37150,Nguyen Lee,HCMC,HCMC,Thailand,VN,"Aug 10, 2024","Sep 05, 2020",54.72,3.523,Air Freight,INTRANSIT,155.39,1712.65,1868.04,NaN,prepaid,2023-04-20 14:36:05,2023-05-02 06:03:18
4,823268,ORD-382996,Nguyen Garcia,Phnom Penh,Phnom Penh,VNM,NaN,2025-09-11,NaN,201.95,1.766,air,LOST,636.16,1341.1,1977.2599999999998,KHR,credit 30d,2023-02-07 00:20:20,2023-10-16 03:38:24

In [56]:
# Naly's work — no missing values in numeric cols
print("=== Missing Values (Naly should have fixed these) ===")
print(df.isnull().sum())

# David's work — no duplicates
print("\n=== Duplicates (David should have removed these) ===")
print(f"Duplicate shipment_ids: {df.duplicated(subset=['shipment_id']).sum()}")

# Menghong's work — date already datetime, year/month/day columns exist
print("\n=== Date columns (Menghong should have created these) ===")
print(df[['ship_date','year','month','day','weekday']].dtypes)

# Tong's work — business logic columns exist
print("\n=== Business logic columns (Tong should have created these) ===")
# e.g. risk_level, customer_category, performance_indicator
print(df.columns.tolist())

=== Missing Values (Naly should have fixed these) ===
shipment_id            39998
order_id               60039
customer_name          27819
origin_city            11856
destination_city       12106
origin_country         62170
destination_country    62198
ship_date              11924
delivery_date          40384
weight_kg              19961
volume_m3              39936
shipping_mode          20042
status                 11784
base_cost_usd              0
surcharge_usd              0
total_cost_usd         71431
currency               82687
payment_terms          84698
created_at                 0
last_update                0
dtype: int64

=== Duplicates (David should have removed these) ===
Duplicate shipment_ids: 74829

=== Date columns (Menghong should have created these) ===

KeyError: "['year', 'month', 'day', 'weekday'] not in index"

In [15]:
# shipment_id is just a unique identifier — no predictive value
cols_to_drop = ['shipment_id']

# Also drop raw date column — Menghong already extracted year/month/day
if 'ship_date' in df.columns:
    cols_to_drop.append('ship_date')

df = df.drop(columns=cols_to_drop, errors='ignore')
print(f"Dropped: {cols_to_drop}")
print(f"Remaining shape: {df.shape}")

Dropped: ['shipment_id', 'ship_date']
Remaining shape: (400000, 18)

In [16]:
from sklearn.preprocessing import LabelEncoder

# shipping_mode has no order — but if ordinal (e.g. risk: Low/Med/High)
# use LabelEncoder
le = LabelEncoder()

# Example: status column
df['status_encoded'] = le.fit_transform(df['status'])
print(le.classes_)  # see the mapping

['??' 'DELIVERED' 'Delivered' 'INTRANSIT' 'LOST' 'RETURNED' 'delivered'
 'in transit' 'lost' 'returned' nan]

In [ ]:
!pip3 install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp314-cp314-macosx_12_0_arm64.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 556.1 kB/s  0:00:14m0:00:0100:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, narwhals, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python3.14 -m pip install --upgrade pip

In [17]:
# shipping_mode: Air, Sea, Road, Rail — no natural order
# One-hot creates binary columns for each category

df = pd.get_dummies(df, columns=['shipping_mode'], prefix='mode', drop_first=True)
# drop_first=True removes one column to avoid multicollinearity
# e.g. if Air=0, Sea=0, Rail=0 → it must be Road (no need for extra column)

print(df.filter(like='mode_').head())

   mode_Air Freight  mode_Sea  mode_TRK  mode_air  mode_rail  mode_sea  \
0             False     False     False     False       True     False
1             False     False      True     False      False     False
2             False     False     False     False      False     False
3              True     False     False     False      False     False
4             False     False     False      True      False     False

   mode_trk  mode_truck
0     False       False
1     False       False
2      True       False
3     False       False
4     False       False

In [18]:
# If status is binary: Delivered vs Not Delivered
# Better to map directly than one-hot
df['is_delivered'] = df['status'].map({'Delivered': 1}).fillna(0).astype(int)

In [19]:
# weight per unit volume — measures cargo density
# Heavy dense cargo costs more to ship
df['density_kg_m3'] = df['weight_kg'] / (df['volume_m3'] + 1e-9)
# +1e-9 prevents division by zero

TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [20]:
# Cost per kg — normalizes cost by weight
df['cost_per_kg'] = df['total_cost_usd'] / (df['weight_kg'] + 1e-9)

# Cost per m3 — normalizes cost by volume
df['cost_per_m3'] = df['total_cost_usd'] / (df['volume_m3'] + 1e-9)

TypeError: can only concatenate str (not "float") to str

In [21]:
# Is it a weekend shipment? (weekday: Mon=0, Sun=6)
df['is_weekend'] = df['weekday'].apply(lambda x: 1 if x >= 5 else 0)

# Quarter of year
df['quarter'] = df['month'].apply(lambda m: (m - 1) // 3 + 1)

# Is peak season? (e.g. Q4: Oct-Dec = high shipping demand)
df['is_peak_season'] = df['quarter'].apply(lambda q: 1 if q == 4 else 0)

KeyError: 'weekday'

In [97]:
# ML models sometimes learn better from categories than raw continuous values
df['weight_category'] = pd.cut(
    df['weight_kg'],
    bins=[0, 50, 200, 500, float('inf')],
    labels=['Light', 'Medium', 'Heavy', 'Very_Heavy']
)

# Then encode it
df['weight_category_encoded'] = df['weight_category'].cat.codes

In [98]:
from scipy.stats import skew

numeric_cols = ['weight_kg', 'volume_m3', 'total_cost_usd',
                'density_kg_m3', 'cost_per_kg', 'cost_per_m3']

for col in numeric_cols:
    sk = skew(df[col].dropna())
    print(f"{col}: skewness = {sk:.2f}")
    if abs(sk) > 1:   # threshold: highly skewed
        df[f'{col}_log'] = np.log1p(df[col])  # log1p = log(1+x), handles 0 safely
        print(f"  → Created {col}_log")

weight_kg: skewness = 9.40
  → Created weight_kg_log
volume_m3: skewness = 0.20
total_cost_usd: skewness = 0.22

KeyError: 'density_kg_m3'

In [24]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# StandardScaler: mean=0, std=1 — use for Logistic Regression
# MinMaxScaler: range [0,1] — use for Neural Nets / KNN

cols_to_scale = ['weight_kg', 'volume_m3', 'total_cost_usd',
                 'density_kg_m3', 'cost_per_kg', 'cost_per_m3']

scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

print("After scaling:")
print(df_scaled[cols_to_scale].describe())

KeyError: "['density_kg_m3', 'cost_per_kg', 'cost_per_m3'] not in index"

In [25]:
# Remove original categorical text columns after encoding
cols_to_remove = [
    'status',           # replaced by is_delivered or status_encoded
    'shipping_mode',    # replaced by mode_Air, mode_Sea, etc.
    'weight_category',  # replaced by weight_category_encoded
]

df_final = df_scaled.drop(columns=cols_to_remove, errors='ignore')
print(f"Final shape: {df_final.shape}")
print(f"Final columns: {df_final.columns.tolist()}")

Final shape: (400000, 26)
Final columns: ['order_id', 'customer_name', 'origin_city', 'destination_city', 'origin_country', 'destination_country', 'delivery_date', 'weight_kg', 'volume_m3', 'base_cost_usd', 'surcharge_usd', 'total_cost_usd', 'currency', 'payment_terms', 'created_at', 'last_update', 'status_encoded', 'mode_Air Freight', 'mode_Sea', 'mode_TRK', 'mode_air', 'mode_rail', 'mode_sea', 'mode_trk', 'mode_truck', 'is_delivered']

In [26]:
# Check 1: No nulls remain
assert df_final.isnull().sum().sum() == 0, "Still has nulls!"

# Check 2: No object dtypes remain (all must be numeric for ML)
object_cols = df_final.select_dtypes(include='object').columns.tolist()
assert len(object_cols) == 0, f"Still has text columns: {object_cols}"

# Check 3: No infinite values
assert not np.isinf(df_final.values).any(), "Has infinite values!"

print("✅ All checks passed. Data is ML-ready.")
print(f"Final dataset: {df_final.shape[0]} rows × {df_final.shape[1]} columns")

AssertionError: Still has nulls!

In [27]:
df_final.to_csv('../data/final_data.csv', index=False)
print("✅ Saved to ../data/final_data.csv")

✅ Saved to ../data/final_data.csv